# TCL File Generated by Component Editor 17.0
# Thu Dec 21 16:03:35 EST 2017
# DO NOT MODIFY


# 
# pcie_matlab_axi_master "PCIe MATLAB as AXI Master" v1.0
#  2017.12.21.16:03:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pcie_matlab_axi_master
# 
set_module_property DESCRIPTION ""
set_module_property NAME pcie_matlab_axi_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MathWorks
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PCIe MATLAB as AXI Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pcie_matlab_axi_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pcie_matlab_axi_master.sv SYSTEM_VERILOG PATH pcie_matlab_axi_master.sv TOP_LEVEL_FILE
add_fileset_file hdlverifier_axi_memcpy.sv SYSTEM_VERILOG PATH hdlverifier_axi_memcpy.sv
add_fileset_file hdlverifier_axilite_memreg.sv SYSTEM_VERILOG PATH hdlverifier_axilite_memreg.sv
add_fileset_file hdlverifier_sync_fifo.sv SYSTEM_VERILOG PATH hdlverifier_sync_fifo.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pcie_matlab_axi_master
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pcie_matlab_axi_master.sv SYSTEM_VERILOG PATH pcie_matlab_axi_master.sv
add_fileset_file hdlverifier_axi_memcpy.sv SYSTEM_VERILOG PATH hdlverifier_axi_memcpy.sv
add_fileset_file hdlverifier_axilite_memreg.sv SYSTEM_VERILOG PATH hdlverifier_axilite_memreg.sv
add_fileset_file hdlverifier_sync_fifo.sv SYSTEM_VERILOG PATH hdlverifier_sync_fifo.sv


# 
# parameters
# 
add_parameter ID_WIDTH INTEGER 1
set_parameter_property ID_WIDTH DEFAULT_VALUE 1
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter AXI_DATA_WIDTH INTEGER 128
set_parameter_property AXI_DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property AXI_DATA_WIDTH DISPLAY_NAME AXI_DATA_WIDTH
set_parameter_property AXI_DATA_WIDTH TYPE INTEGER
set_parameter_property AXI_DATA_WIDTH UNITS None
set_parameter_property AXI_DATA_WIDTH ALLOWED_RANGES {128 256}
set_parameter_property AXI_DATA_WIDTH HDL_PARAMETER true
add_parameter AXI_ADDR_WIDTH INTEGER 32
set_parameter_property AXI_ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property AXI_ADDR_WIDTH DISPLAY_NAME AXI_ADDR_WIDTH
set_parameter_property AXI_ADDR_WIDTH TYPE INTEGER
set_parameter_property AXI_ADDR_WIDTH UNITS None
set_parameter_property AXI_ADDR_WIDTH ALLOWED_RANGES {32}
set_parameter_property AXI_ADDR_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point axs_s0
# 
add_interface axs_s0 axi4lite end
set_interface_property axs_s0 associatedClock clock
set_interface_property axs_s0 associatedReset resetn
set_interface_property axs_s0 readAcceptanceCapability 1
set_interface_property axs_s0 writeAcceptanceCapability 1
set_interface_property axs_s0 combinedAcceptanceCapability 1
set_interface_property axs_s0 readDataReorderingDepth 1
set_interface_property axs_s0 bridgesToMaster ""
set_interface_property axs_s0 ENABLED true
set_interface_property axs_s0 EXPORT_OF ""
set_interface_property axs_s0 PORT_NAME_MAP ""
set_interface_property axs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property axs_s0 SVD_ADDRESS_GROUP ""

add_interface_port axs_s0 axis_awaddr awaddr Input 5
add_interface_port axs_s0 axis_awvalid awvalid Input 1
add_interface_port axs_s0 axis_awready awready Output 1
add_interface_port axs_s0 axis_wdata wdata Input 32
add_interface_port axs_s0 axis_wvalid wvalid Input 1
add_interface_port axs_s0 axis_wready wready Output 1
add_interface_port axs_s0 axis_bvalid bvalid Output 1
add_interface_port axs_s0 axis_bready bready Input 1
add_interface_port axs_s0 axis_araddr araddr Input 5
add_interface_port axs_s0 axis_arvalid arvalid Input 1
add_interface_port axs_s0 axis_arready arready Output 1
add_interface_port axs_s0 axis_rdata rdata Output 32
add_interface_port axs_s0 axis_rvalid rvalid Output 1
add_interface_port axs_s0 axis_rready rready Input 1
add_interface_port axs_s0 axis_arprot arprot Input 3
add_interface_port axs_s0 axis_awprot awprot Input 3
add_interface_port axs_s0 axis_bresp bresp Output 2
add_interface_port axs_s0 axis_rresp rresp Output 2
add_interface_port axs_s0 axis_wstrb wstrb Input 4


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock aclk clk Input 1


# 
# connection point resetn
# 
add_interface resetn reset end
set_interface_property resetn associatedClock clock
set_interface_property resetn synchronousEdges DEASSERT
set_interface_property resetn ENABLED true
set_interface_property resetn EXPORT_OF ""
set_interface_property resetn PORT_NAME_MAP ""
set_interface_property resetn CMSIS_SVD_VARIABLES ""
set_interface_property resetn SVD_ADDRESS_GROUP ""

add_interface_port resetn aresetn reset_n Input 1


# 
# connection point axm_pcie
# 
add_interface axm_pcie axi4 start
set_interface_property axm_pcie associatedClock clock
set_interface_property axm_pcie associatedReset resetn
set_interface_property axm_pcie readIssuingCapability 2
set_interface_property axm_pcie writeIssuingCapability 2
set_interface_property axm_pcie combinedIssuingCapability 4
set_interface_property axm_pcie ENABLED true
set_interface_property axm_pcie EXPORT_OF ""
set_interface_property axm_pcie PORT_NAME_MAP ""
set_interface_property axm_pcie CMSIS_SVD_VARIABLES ""
set_interface_property axm_pcie SVD_ADDRESS_GROUP ""

add_interface_port axm_pcie axm1_awaddr awaddr Output 32
add_interface_port axm_pcie axm1_awprot awprot Output 3
add_interface_port axm_pcie axm1_awvalid awvalid Output 1
add_interface_port axm_pcie axm1_awready awready Input 1
add_interface_port axm_pcie axm1_wdata wdata Output AXI_DATA_WIDTH
add_interface_port axm_pcie axm1_wlast wlast Output 1
add_interface_port axm_pcie axm1_wvalid wvalid Output 1
add_interface_port axm_pcie axm1_wready wready Input 1
add_interface_port axm_pcie axm1_bvalid bvalid Input 1
add_interface_port axm_pcie axm1_bready bready Output 1
add_interface_port axm_pcie axm1_araddr araddr Output 32
add_interface_port axm_pcie axm1_arprot arprot Output 3
add_interface_port axm_pcie axm1_arvalid arvalid Output 1
add_interface_port axm_pcie axm1_arready arready Input 1
add_interface_port axm_pcie axm1_rdata rdata Input AXI_DATA_WIDTH
add_interface_port axm_pcie axm1_rvalid rvalid Input 1
add_interface_port axm_pcie axm1_rready rready Output 1
add_interface_port axm_pcie axm1_arburst arburst Output 2
add_interface_port axm_pcie axm1_awburst awburst Output 2
add_interface_port axm_pcie axm1_arcache arcache Output 4
add_interface_port axm_pcie axm1_arid arid Output 1
add_interface_port axm_pcie axm1_arlen arlen Output 8
add_interface_port axm_pcie axm1_arlock arlock Output 1
add_interface_port axm_pcie axm1_arqos arqos Output 4
add_interface_port axm_pcie axm1_arsize arsize Output 3
add_interface_port axm_pcie axm1_awcache awcache Output 4
add_interface_port axm_pcie axm1_awid awid Output 1
add_interface_port axm_pcie axm1_awlen awlen Output 8
add_interface_port axm_pcie axm1_awlock awlock Output 1
add_interface_port axm_pcie axm1_awqos awqos Output 4
add_interface_port axm_pcie axm1_awsize awsize Output 3
add_interface_port axm_pcie axm1_bid bid Input 1
add_interface_port axm_pcie axm1_bresp bresp Input 2
add_interface_port axm_pcie axm1_rid rid Input 1
add_interface_port axm_pcie axm1_rlast rlast Input 1
add_interface_port axm_pcie axm1_rresp rresp Input 2
add_interface_port axm_pcie axm1_wstrb wstrb Output AXI_DATA_WIDTH/8


# 
# connection point axm_app
# 
add_interface axm_app axi4 start
set_interface_property axm_app associatedClock clock
set_interface_property axm_app associatedReset resetn
set_interface_property axm_app readIssuingCapability 2
set_interface_property axm_app writeIssuingCapability 2
set_interface_property axm_app combinedIssuingCapability 4
set_interface_property axm_app ENABLED true
set_interface_property axm_app EXPORT_OF ""
set_interface_property axm_app PORT_NAME_MAP ""
set_interface_property axm_app CMSIS_SVD_VARIABLES ""
set_interface_property axm_app SVD_ADDRESS_GROUP ""

add_interface_port axm_app axm2_awaddr awaddr Output 32
add_interface_port axm_app axm2_awprot awprot Output 3
add_interface_port axm_app axm2_awvalid awvalid Output 1
add_interface_port axm_app axm2_awready awready Input 1
add_interface_port axm_app axm2_wdata wdata Output AXI_DATA_WIDTH
add_interface_port axm_app axm2_wlast wlast Output 1
add_interface_port axm_app axm2_wvalid wvalid Output 1
add_interface_port axm_app axm2_wready wready Input 1
add_interface_port axm_app axm2_bvalid bvalid Input 1
add_interface_port axm_app axm2_bready bready Output 1
add_interface_port axm_app axm2_araddr araddr Output 32
add_interface_port axm_app axm2_arprot arprot Output 3
add_interface_port axm_app axm2_arvalid arvalid Output 1
add_interface_port axm_app axm2_arready arready Input 1
add_interface_port axm_app axm2_rdata rdata Input AXI_DATA_WIDTH
add_interface_port axm_app axm2_rvalid rvalid Input 1
add_interface_port axm_app axm2_rready rready Output 1
add_interface_port axm_app axm2_awburst awburst Output 2
add_interface_port axm_app axm2_arburst arburst Output 2
add_interface_port axm_app axm2_arcache arcache Output 4
add_interface_port axm_app axm2_arid arid Output 1
add_interface_port axm_app axm2_arlen arlen Output 8
add_interface_port axm_app axm2_arlock arlock Output 1
add_interface_port axm_app axm2_arqos arqos Output 4
add_interface_port axm_app axm2_arsize arsize Output 3
add_interface_port axm_app axm2_awcache awcache Output 4
add_interface_port axm_app axm2_awid awid Output 1
add_interface_port axm_app axm2_awlen awlen Output 8
add_interface_port axm_app axm2_awlock awlock Output 1
add_interface_port axm_app axm2_awqos awqos Output 4
add_interface_port axm_app axm2_awsize awsize Output 3
add_interface_port axm_app axm2_bid bid Input 1
add_interface_port axm_app axm2_bresp bresp Input 2
add_interface_port axm_app axm2_rid rid Input 1
add_interface_port axm_app axm2_rlast rlast Input 1
add_interface_port axm_app axm2_rresp rresp Input 2
add_interface_port axm_app axm2_wstrb wstrb Output AXI_DATA_WIDTH/8

