# TCL File Generated by Component Editor 15.1
# Tue Aug 23 17:06:20 EDT 2016
# DO NOT MODIFY


# 
# hdlverifier_axi_master "hdlverifier_axi_master" v1.0
#  2016.08.23.17:06:20
# JTAG AXI Master
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module hdlverifier_axi_master
# 
set_module_property DESCRIPTION "MATLAB as AXI Master"
set_module_property NAME "MATLAB_as_AXI_Master"
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "MathWorks"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "MATLAB as AXI Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdlverifier_axi_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdlverifier_axi_master.sv SYSTEM_VERILOG PATH hdlverifier_axi_master.sv TOP_LEVEL_FILE
add_fileset_file hdlverifier_jtag_core.v VERILOG PATH hdlverifier_jtag_core.v
add_fileset_file hdlverifier_jtag_vendor_ip1.v VERILOG PATH hdlverifier_jtag_vendor_ip1.v


# 
# parameters
# 
add_parameter          JTAG_ID  INTEGER 56 "JTAG ID"
set_parameter_property JTAG_ID  UNITS None
set_parameter_property JTAG_ID  AFFECTS_GENERATION false
set_parameter_property JTAG_ID  HDL_PARAMETER true
set_parameter_property JTAG_ID  ALLOWED_RANGES 1:127

add_parameter          ID_WIDTH  INTEGER 1 "ID WIDTH"
set_parameter_property ID_WIDTH  UNITS None
set_parameter_property ID_WIDTH  AFFECTS_GENERATION false
set_parameter_property ID_WIDTH  HDL_PARAMETER true
set_parameter_property ID_WIDTH  ALLOWED_RANGES 1:5


add_parameter          AXI_DATA_WIDTH  INTEGER 32 "AXI Data Width"
set_parameter_property AXI_DATA_WIDTH  UNITS None
set_parameter_property AXI_DATA_WIDTH  AFFECTS_GENERATION false
set_parameter_property AXI_DATA_WIDTH  HDL_PARAMETER true
set_parameter_property AXI_DATA_WIDTH  ALLOWED_RANGES 32,64
set_parameter_property AXI_DATA_WIDTH  HDL_PARAMETER true

add_parameter          AXI_ADDR_WIDTH  INTEGER 32 "AXI Data Width"
set_parameter_property AXI_ADDR_WIDTH  UNITS None
set_parameter_property AXI_ADDR_WIDTH  AFFECTS_GENERATION false
set_parameter_property AXI_ADDR_WIDTH  HDL_PARAMETER true
set_parameter_property AXI_ADDR_WIDTH  ALLOWED_RANGES 32,64
set_parameter_property AXI_ADDR_WIDTH  HDL_PARAMETER true

# 
# display items
# 


# 
# connection point axm_m0
# 
add_interface axm_m0 axi4 start
set_interface_property axm_m0 associatedClock aclk
set_interface_property axm_m0 associatedReset aresetn
set_interface_property axm_m0 readIssuingCapability 1
set_interface_property axm_m0 writeIssuingCapability 1
set_interface_property axm_m0 combinedIssuingCapability 1
set_interface_property axm_m0 ENABLED true
set_interface_property axm_m0 EXPORT_OF ""
set_interface_property axm_m0 PORT_NAME_MAP ""
set_interface_property axm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property axm_m0 SVD_ADDRESS_GROUP ""

add_interface_port axm_m0 axi4m_awaddr awaddr Output AXI_ADDR_WIDTH
add_interface_port axm_m0 axi4m_awprot awprot Output 3
add_interface_port axm_m0 axi4m_awvalid awvalid Output 1
add_interface_port axm_m0 axi4m_awready awready Input 1
add_interface_port axm_m0 axi4m_wdata wdata Output AXI_DATA_WIDTH
add_interface_port axm_m0 axi4m_wlast wlast Output 1
add_interface_port axm_m0 axi4m_wvalid wvalid Output 1
add_interface_port axm_m0 axi4m_wready wready Input 1
add_interface_port axm_m0 axi4m_bvalid bvalid Input 1
add_interface_port axm_m0 axi4m_bready bready Output 1
add_interface_port axm_m0 axi4m_araddr araddr Output AXI_ADDR_WIDTH
add_interface_port axm_m0 axi4m_arprot arprot Output 3
add_interface_port axm_m0 axi4m_arvalid arvalid Output 1
add_interface_port axm_m0 axi4m_arready arready Input 1
add_interface_port axm_m0 axi4m_rdata rdata Input AXI_DATA_WIDTH
add_interface_port axm_m0 axi4m_rvalid rvalid Input 1
add_interface_port axm_m0 axi4m_rready rready Output 1
add_interface_port axm_m0 axi4m_arburst arburst Output 2
add_interface_port axm_m0 axi4m_arcache arcache Output 4
add_interface_port axm_m0 axi4m_arlen arlen Output 8
add_interface_port axm_m0 axi4m_arlock arlock Output 1
add_interface_port axm_m0 axi4m_arqos arqos Output 4
add_interface_port axm_m0 axi4m_arsize arsize Output 3
add_interface_port axm_m0 axi4m_awburst awburst Output 2
add_interface_port axm_m0 axi4m_awcache awcache Output 4
add_interface_port axm_m0 axi4m_awid awid Output ID_WIDTH
add_interface_port axm_m0 axi4m_awlen awlen Output 8
add_interface_port axm_m0 axi4m_awlock awlock Output 1
add_interface_port axm_m0 axi4m_awqos awqos Output 4
add_interface_port axm_m0 axi4m_awsize awsize Output 3
add_interface_port axm_m0 axi4m_bresp bresp Input 2
add_interface_port axm_m0 axi4m_rid rid Input 1
add_interface_port axm_m0 axi4m_rlast rlast Input 1
add_interface_port axm_m0 axi4m_rresp rresp Input 2
add_interface_port axm_m0 axi4m_wstrb wstrb Output AXI_DATA_WIDTH/8
add_interface_port axm_m0 axi4m_arid arid Output ID_WIDTH
add_interface_port axm_m0 axi4m_bid bid Input 1



# 
# connection point aclk
# 
add_interface aclk clock end
set_interface_property aclk clockRate 0
set_interface_property aclk ENABLED true
set_interface_property aclk EXPORT_OF ""
set_interface_property aclk PORT_NAME_MAP ""
set_interface_property aclk CMSIS_SVD_VARIABLES ""
set_interface_property aclk SVD_ADDRESS_GROUP ""

add_interface_port aclk aclk clk Input 1


# 
# connection point aresetn
# 
add_interface aresetn reset end
set_interface_property aresetn associatedClock aclk
set_interface_property aresetn synchronousEdges DEASSERT
set_interface_property aresetn ENABLED true
set_interface_property aresetn EXPORT_OF ""
set_interface_property aresetn PORT_NAME_MAP ""
set_interface_property aresetn CMSIS_SVD_VARIABLES ""
set_interface_property aresetn SVD_ADDRESS_GROUP ""

add_interface_port aresetn aresetn reset_n Input 1

